name: Qualité Code Action

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Download PHP_CodeSniffer
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - name: Run PHP_CodeSniffer
      run: |
        php phpcs.phar --standard="${{github.workspace}}/test/phpcs/Symfony"
