name: Test PHPCS
on: [push, pull_request]
jobs: 
  demo: 
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Installer PHPCS
        run: composer global require "squizlabs/php_codesniffer=*"
      
      - name: tester PHPCS sur MesDates.php
        run: ~/.composer/vendor/bin/phpcs --standard=PSR1,PSR12 ./src
      
      - name: afficher date de demain
        run: php ./src/TD5.php
